### ISSUE TITLE
直接网盘提取的链接，第一次可以播放，第二次就报错url too long

### ISSUE THREAD

**Issue by Prince-cool** [synctv-org/synctv#10]
链接地址：https://ccp-bj29-video-preview.oss-enet.aliyuncs.com/lt/049481C1F8FAE0FAED5C3D2A118D180415335C78_2164517990__sha1_bj29_e2f29c75/FHD/media.m3u8?di=bj29&dr=338032582&f=64fc2574254c0ec47e55485786e6d00544067892&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5beLMrHv71Z5qimVkeAnkwMdthBhPKZ0Tz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNUPUMniLqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABlIGavEYPi6FdgM0Vfv6klpiaZgfgBqdcFiakuv%2BWzx%2BJ9sOLi0ySaRgLEVq2HTG6feMfhEt0%2BcvYJD%2FPJb12QxU0n4ITWfdHdDwIL5ZdYjB4sBzLrcEW5Wobtsyzb18RT0HsfXfc8GVaUEI0IyyALOwEoqGnV8tklQh0SxWNqrUgAA%3D%3D&u=9498423caffc495b8f2e9ded422718d2&x-oss-access-key-id=STS.NUkgpsRbxQjMTa1zLYzWmk723&x-oss-expires=1697482104&x-oss-process=hls%2Fsign%2Cparams_ZGksZHIsZix1&x-oss-signature=B1Hu%2BbJ2TimPDff2DrVtZqYlKRHdz6d3Qta%2F4ouJGE0%3D&x-oss-signature-version=OSS2

可播放的

**Comment by Prince-cool** [comment]
换了一个链接就不会报这个错了：https://cn-beijing-data.aliyundrive.net/WWMsK8Og%2F73803872%2F64f9a3ecea817df7332a4b0ea97335e690ec4e6e%2F64f9a3ecba9b50d52c304045bc55857d5a5956db?di=bj29&dr=338032582&f=64fc2574254c0ec47e55485786e6d00544067892&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fdHI3hqYhM2JWfR3TopnYMZMtfhvTTkDz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNXbyVwKMqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABgPFtEP8ef6rh24TcCLWyQgnplNr%2BQK92agWzr1Pye9TwT43uacDn99WeYDxSp80IVNjeb3ucDe6Gnm25DaZRtZL8pit7JPQ9fZKKROTiMdxmeC%2BkyNlL%2FRH9kMKb3HFhs3uFgABwPOqv%2BzAcJBebBZ0kwqqLV724j8BvhjuUsKIgAA%3D%3D&u=254808010963075794&x-oss-access-key-id=STS.NThW7UDWmoWtERYBvYhDsi1xr&x-oss-expires=1697468603&x-oss-signature=MePUHvzkwIznJXTwBkQaJ9RVqGOUhOmzNzAHe2bLn5A%3D&x-oss-signature-version=OSS2

**Comment by zijiren233** [comment]
感谢反馈，`url too long`会在下一次更新中修复

**Comment by huankong233** [comment]
这个可以直接用alist，还可以防止过期等问题

**Comment by zijiren233** [comment]
已修复
