### ISSUE TITLE
分享房间按钮复制链接在chrome浏览器显示浏览器不支持Clipboard API

### ISSUE THREAD

**Issue by wibi8bo** [synctv-org/synctv#100]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MinionsZQG** [comment]
Microsoft Edge
版本 122.0.2365.80 (正式版本) (64 位)
问题相同

**Comment by LazyCreeper** [comment]
浏览器限制，需要使用https
