### ISSUE TITLE
能不能新增一个端口修改啊，或者修改一下默认端口

### ISSUE THREAD

**Issue by autunn** [synctv-org/synctv#101]
容器默认使用8080端口，但是我的8080端口被qb占用了，想要搭建完以后再修改容器端口号，但是没有找到相关设置

**Comment by BubbleBearU** [comment]
docker可以修改端口映射

**Comment by BubbleBearU** [comment]
是什么系统环境？ 或者可以通过docker compose修改

**Comment by autunn** [comment]
我试过通过docker compose修改端口，没办法启动，提示端口已经被占用，我是群晖7.2

**Comment by BubbleBearU** [comment]
> 我试过通过docker compose修改端口，没办法启动，提示端口已经被占用，我是群晖7.2

群晖的不是可以直接修改吗   container manager左侧输入映射到的群晖端口  右侧是docker内部端口   
比如左侧10086  右侧8080 访问群晖端口10086就可以了

**Comment by BubbleBearU** [comment]
> 我试过通过docker compose修改端口，没办法启动，提示端口已经被占用，我是群晖7.2

另外有第三方的SyncTV群晖套件,我这边用的就是套件

**Comment by BubbleBearU** [comment]
套件中心→社群→设置→套件来源 新增https://spk7.imnks.com/

**Comment by autunn** [comment]
我用的docker

**Comment by BubbleBearU** [comment]
> 我用的docker

什么机型的群晖    docker也是能修改端口映射的啊

**Comment by autunn** [comment]
黑裙 918，应该不是群晖的问题，我别的程序镜像能直接改，只有这个不能改，就很奇怪，我以为锁死8080端口了，所以来问问

**Comment by BubbleBearU** [comment]
> 黑裙 918，应该不是群晖的问题，我别的程序镜像能直接改，只有这个不能改，就很奇怪，我以为锁死8080端口了，所以来问问

你的意思是没有这一项吗 你可以新建直接映射就行了
