### ISSUE TITLE
emby和alist添加不了ipv6域名解析

### ISSUE THREAD

**Issue by Jogger7** [synctv-org/synctv#108]
地址是域名解析的ipv6地址时提示Post "http://*.*.*:5244/api/auth/login/hash": dial tcp: lookup *.*.*: no such host

**Comment by zijiren233** [comment]
docker部署的吗，docker内部一般没有ipv6，得手动开启

**Comment by Jogger7** [comment]
不是docker 直接在windows下的

**Comment by waitfortea** [comment]
一、端口错误，
二、防火墙的问题，确保路由器允许ipv6转发到Lan内windows主机上，并且windows防火墙允许通过，可以在测试的时候把windows防火墙关掉，
