### ISSUE TITLE
无法支持alist中的一些网盘

### ISSUE THREAD

**Issue by Smart-zsw** [synctv-org/synctv#110]
**Describe the bug**
目前经过反复测试发现。
alist中完美支持的存储（我有的存储），只能够支持阿里云盘、天翼云盘、Pikpak、OneDrive可以正常播放。
alist中确定不支持的存储（我有的存储），本地存储、115网盘、夸克网盘。
谷歌云盘（某些情况下可以，某些情况下不可以），这个具体我也不清楚问题。
其余没有提到的网盘并没有，所以没有进行测试。

**To Reproduce**
直接启动播放不支持网盘中的视频，则直接无法连接，视频左上角显示重新连接，之后立刻失败无法播放，失败后再次点击毫无反应。

**Expected behavior**
希望可以优先支持（按照优先级顺序）：115网盘、本地存储、夸克网盘、曲奇网盘中的视频播放。

**Screenshots**
![image](https://github.com/synctv-org/synctv/assets/98108711/db765385-e5e1-4138-b671-4ce26b52cfaf)
![image](https://github.com/synctv-org/synctv/assets/98108711/f16938c0-5853-4c03-a64e-64633cad7ce9)

**Desktop (please complete the following information):**
全平台客户端。

**Smartphone (please complete the following information):**
全平台客户端。

**Additional context**
感谢开发大佬！

**Comment by Hubray** [comment]
本地存储不支持播放这个我也发现了，左上角一直弹出重新连接次数。但是会偶尔能播放，并且找不到浮现规律

**Comment by zijiren233** [comment]
1. 本地存储如果你通过内网访问alist
- 如果你的播放设备也在内网，会触发浏览器的安全限制，因为浏览器不允许访问非本机的内网
- 如果你的设备与服务器不在同一网络（不在同一内网），那么会导致播放地址变成内网地址，所以无法访问

解决办法：
- 开启SyncTV的视频代理功能
- 使用非内网地址访问alist

2. 115网盘和夸克由于开发者没有账号所以无法测试，如果可以提供alist测试账户以供复现问题则可以修复，可以在readme中找到synctv的telegram群组以及我的邮件

**Comment by xuze1993** [comment]
这个似乎是alist的问题，在alist上就是这样。如果alist上能播放，那么synctv也是正常的。
我挂的是百度云，视频一大就这样子，小视频没问题。走的本地代理，机器性能和带宽应该没问题的。

**Comment by Hubray** [comment]
> 这个似乎是alist的问题，在alist上就是这样。如果alist上能播放，那么synctv也是正常的。 我挂的是百度云，视频一大就这样子，小视频没问题。走的本地代理，机器性能和带宽应该没问题的。

这各我用两个alist测试过，目前ailst支持比较好的就是阿里云盘，alist本地资源播放会有左上角重新连接的提示循环出现

**Comment by JamaisVuu** [comment]
一样的情况，同样资源115无法播放，阿里云盘上的完美支持

**Comment by zijiren233** [comment]
> 一样的情况，同样资源115无法播放，阿里云盘上的完美支持

使用的版本是？
