### ISSUE TITLE
房间列表可以显示本人的隐藏直播间

### ISSUE THREAD

**Issue by A1KESH1** [synctv-org/synctv#111]
![image](https://github.com/synctv-org/synctv/assets/42016325/73652b8e-bf95-4dad-b73d-d475af5aa667)
房间列表可以显示本人的隐藏直播间（对其他人隐藏）

**Comment by zijiren233** [comment]
房间列表是公共接口，暂时不支持这么做，只能到个人信息界面中看到自己的所有房间
