### ISSUE TITLE
房间内创建直播后，在 obs 填写了推流信息，但是开始直播 obs 提示无法连接到服务器

### ISSUE THREAD

**Issue by wibi8bo** [synctv-org/synctv#122]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://github.com/synctv-org/synctv/assets/91667528/68825c31-622a-45a9-82c8-dbd848be909a)

**Comment by zijiren233** [comment]
信息太少了，不过提醒几点容易出现问题的地方
是否开启了反向代理，包括但不限于nginx, cdn...，因为这类http代理并不能处理rtmp协议，你需要开放rtmp端口，比如默认的8080端口，并在SyncTV网页这是中将RTMP的HOST设置为可以访问到源服务器的 `ip:port`
