### ISSUE TITLE
无进度条

### ISSUE THREAD

**Issue by xuze1993** [synctv-org/synctv#124]
随便找了个m3u8格式的直播源，播放时只能暂停但没有进度条。
浏览器或其他播放器没什么问题。

https://svipsvip.ffzy-online5.com/20240407/25752_7ee666a9/2000k/hls/mixed.m3u8

有点奇怪，内网启动的过了下cf的代理就有进度条了。。

**Comment by zijiren233** [comment]
可能是缓存问题，最新版删除了前端缓存
