### ISSUE TITLE
添加的部分emby视频没有声音

### ISSUE THREAD

**Issue by Gathershare** [synctv-org/synctv#126]
添加的部分emby视频没有声音，在emby中播放是有声音的。
synctv能播放出声音的 格式
视频：4K HEVC 音频：Und AAC stereo (Default)
视频：1080p H264  音频：Korean AAC stereo (Default)
synctv不能播放出声音的格式
视频：1080p H264 音频：Chinese Simplified EAC3 5.1 (Default)

**Comment by zijiren233** [comment]
v0.5.2 已实现自动转码
