### ISSUE TITLE
Mail test report a error"email unbound"

### ISSUE THREAD

**Issue by HelloMusician** [synctv-org/synctv#127]
I have set all the email configurations and when I clicked the test button it ocurred a error"email unbound"

I hope to use the email function.

**Screenshots**
![image](https://github.com/synctv-org/synctv/assets/105097307/7ab868ff-8637-496b-8b2e-47f760612ff0)

**Desktop (please complete the following information):**
 - OS: linux dsm7.2 update 5
 - Browser: edge latest

**Comment by zijiren233** [comment]
If you haven't bound your email address yet, you need to fill in the email address when you click Send Test Email.
