### ISSUE TITLE
播放m3u8文件时切片非常规格式无法播放

### ISSUE THREAD

**Issue by anwen-anyi** [synctv-org/synctv#13]
**Describe the bug**

播放`m3u8`链接时切片非常规格式无法播放，切片格式是 .jpg格式

**To Reproduce**
控制台错误信息，[切片文件下载 -->前任1：前任攻略.zip](https://github.com/synctv-org/synctv/files/12980990/1.zip)

![3A(R($JLBO81 M0`@ $0F67](https://github.com/synctv-org/synctv/assets/56105412/b8bd1232-0128-4a08-9cef-8ee209d6b24e)

**Expected behavior**
目前非常规 m3u8切片无法播放，希望后期可以支持一下

**Screenshots**
参考 `To Reproduce`

**Desktop (please complete the following information):**
Windows 10  `Google Chrome 117.0.5938.92`

**Smartphone (please complete the following information):**

N/A

**Additional context**
N/A

**Comment by zijiren233** [comment]
已修复
