### ISSUE TITLE
全屏看视频会自动退出

### ISSUE THREAD

**Issue by euukey** [synctv-org/synctv#130]
全屏看视频，到了缓存完的分界点就会退出全屏。

手动拖动到分界点前一段时间无法复现，必须要观看。

 OS: Windows 11 23H2
Browser：360极速浏览器X 22.3.1002.64 
Version：5.0.0

**Comment by Hubray** [comment]
我测试下来是阿里云盘的视频是这样，PC和安卓端都有看视频会退出的情况，间隔大概是14分钟

**Comment by zijiren233** [comment]
因为这个：https://github.com/synctv-org/synctv/issues/57

**Comment by euukey** [comment]
> 因为这个：#57

目前没有好的解决方案吗

**Comment by oneisall8955** [comment]
> 因为这个：#57
@zijiren233 这个问题仍然存在，电脑端还好，手机端会因为弹出停住播放，需要手动点一下才能继续播放

**Comment by zijiren233** [comment]
已修复 https://github.com/synctv-org/synctv-web/commit/ef9c380edb48a8ee65b1f5ee76fb0da838ab159e
