### ISSUE TITLE
0.5.0创建数据库失败

### ISSUE THREAD

**Issue by A1KESH1** [synctv-org/synctv#132]
0.5.0创建数据库失败
![image](https://github.com/synctv-org/synctv/assets/42016325/4ea1cc7a-267c-419a-bc2b-db7eb10d3e83)

**Comment by zijiren233** [comment]
已修复 https://github.com/synctv-org/synctv/commit/65d4d6757c3b803cb70bb72fefeaeba528f2e9fd
