### ISSUE TITLE
放视频没有画面只有声音，emby的影片选择只支持电影，其他的加载不出来

### ISSUE THREAD

**Issue by SagoLu** [synctv-org/synctv#136]
之前以为只是mkv不行，后面换了MP4还是一样只有声音。
在选择影片时，选择电视剧，可以加载列表，但是再次点击电视剧名称进入选择某季的时候会一直加载中。
我用的docker部署，emby在同一个docker上，不知道是有什么地方没弄对

**Comment by SagoLu** [comment]
加载目录的问题，经过调试发现卡在emby.go的genPath目录，是个死循环，由于不会golang，不知道怎么解决这个问题

**Comment by zijiren233** [comment]
emby vendor在synctv中支持并不完善，需要重构，但是需要的精力可能很大：https://github.com/synctv-org/vendors/tree/main/vendors/emby

**Comment by zijiren233** [comment]
加在目录的问题能否提供一个emby账号用来测试
