### ISSUE TITLE
移动端点击全屏后还是竖屏

### ISSUE THREAD

**Issue by mycode233** [synctv-org/synctv#137]
移动端点击全屏按钮后，还是竖屏。得手动开启屏幕旋转，并旋转手机才可以。

在竖屏状态下（图1），点击全屏按钮，会变成图2样子，并没有实现全屏。

需要手机开启旋转，旋转至横屏才能全屏
![1x](https://github.com/synctv-org/synctv/assets/50506732/b56581dc-2060-46ea-8d2d-ec8749e6b68b)
![2](https://github.com/synctv-org/synctv/assets/50506732/d2263052-e346-41b7-b785-f5a48a0048f1)

OS: 安卓14
Browser：EDGE 122.0.2365.56
Version：0.5.1

**Comment by zijiren233** [comment]
这个很难复现啊，没办法修

**Comment by mycode233** [comment]
在竖屏状态下（图1），点击全屏按钮，会变成图2样子，并没有实现全屏。

需要手机开启旋转，旋转至横屏才能全屏
![1x](https://github.com/synctv-org/synctv/assets/50506732/b56581dc-2060-46ea-8d2d-ec8749e6b68b)
![2](https://github.com/synctv-org/synctv/assets/50506732/d2263052-e346-41b7-b785-f5a48a0048f1)

**Comment by mycode233** [comment]
> 这个很难复现啊，没办法修

不好意思，可能我描述不太具体，我补充了图片，您看一下

**Comment by zijiren233** [comment]
这个不知道咋修，可能得开手机旋转

**Comment by zijiren233** [comment]
fix on v0.7.1
