### ISSUE TITLE
非房主用户，以登录情况下，无法切换影片

### ISSUE THREAD

**Issue by oneisall8955** [synctv-org/synctv#152]
房间已经给了用户切换影片权限，但是非房主用户，无法切影片。如下图所示：

![image](https://github.com/synctv-org/synctv/assets/44989283/6d746a03-d711-4e61-ac43-a6a103a0c740)

![image](https://github.com/synctv-org/synctv/assets/44989283/b1e7b7d4-d57d-4581-bc7e-ccad95184248)

**Comment by zijiren233** [comment]
这个只是默认权限，用户首次加入房间的时候才生效
你需要在成员中单独设置已加入的用户的权限

**Comment by oneisall8955** [comment]
> 这个只是默认权限，用户首次加入房间的时候才生效 你需要在成员中单独设置已加入的用户的权限

是在此处管理吗？这里只有设置为管理这个权限调整

<img width="1638" alt="image" src="https://github.com/synctv-org/synctv/assets/44989283/ac0eb2ec-5057-45e5-896e-8c620b0c2253">

**Comment by zijiren233** [comment]
点击权限组列蓝色的字

**Comment by oneisall8955** [comment]
> 点击权限组列蓝色的字

谢谢，已经设置好生效了，不过隐蔽了点
