### ISSUE TITLE
影片列表以目录形式展现

### ISSUE THREAD

**Issue by oneisall8955** [synctv-org/synctv#153]
感谢十分优秀的项目，在使用过程中感到已经十分完善了。

在这里提个小建议，影片列表是否可以用目录形式存储？

这个需求暂时没想好怎么实现比较好，思路比较乱，想的比较多。
我想这里可以作为比较通用的形式，不过有很大的入侵性。

---------------------------------------
先说下我目前需求场景：
- 添加影片，来源使用 alist
- alist 选取影片，只能一个目录一个目录的多选影片添加到列表
- 我和朋友一起看的是学习教程类视频，例如：Python 入门到精通
- 教程目录如下：
    ```
    Python 入门到精通
    - 01 介绍
    - - 01-01 Python 介绍介应用场景.mp4
    - 02 基础
    - - 02-01 window 和 Linux 安装Python.mp4
    - - 02-02 基础语法.mp4
    - - ......
    - 03 高级
    - - ......
    ```
- 上述是以目录为基础树形结构
- 我想把`Python 入门到精通` 整个目录添加到播放列表，并且内容是动态的。例如某一天这个教程更新了，这里不需要再手动添加一次，只需要在页面刷新一下即可。在播放列表中可以浏览整个目录选取视频来播放

不仅是教程类，剧集类别也有这个问题，我用 alist 配合了 aliyun-driver-subscribe 项目自动追更了上游分享的剧集，每次更新，我都需要在 synctv 重新添加更新好的视频，比较麻烦，如果是一个目录形式，就比较好解决了。

初步我的想法是目录有远程目录（alist ，tvbox 解析爬虫等）和手工创建区分这样。后续想越过于复杂，怕对普通用户不好

**Comment by zijiren233** [comment]
已支持

**Comment by oneisall8955** [comment]
灰常感谢~非常完美~
