### ISSUE TITLE
支持RTMP直播流

### ISSUE THREAD

**Issue by fuckhere** [synctv-org/synctv#158]
我有一个rtmp的直播流，在直播流、代理直播流中均不能添加rtmp，需要http。或者有什么办法可以将rtmp转http输出？

**Comment by fuckhere** [comment]
我使用了hls转成http，在vlc等都可以访问，但是在synctv中一直显示不了

**Comment by zijiren233** [comment]
你需要在代理直播流中输入你的rtmp拉流地址，如：`rtmp://127.0.0.1:1234/asdasd`

**Comment by fuckhere** [comment]
貌似是bug，他提示"bvid or epid is empty"，我输入的"rtmp://127.0.0.1/live/obs"

**Comment by fuckhere** [comment]
> 可以使用SRS自建一个媒体服务器，然后在播放列表了添加自己的FLV直播链接，推流往SRS服务器上推，这样最简单。

我用的nginx的hls，rtmp和http都可以用，在vlc都可以进去，但是synctv不行

**Comment by zijiren233** [comment]
已修复
