### ISSUE TITLE
[建议]空房间自动销毁

### ISSUE THREAD

**Issue by swRains** [synctv-org/synctv#16]
我看示例站点的房间已经五十多个了，很多还是很久之前开的，是否可以考虑设置个房间的TTL，无人在的房间超过8小时自动销毁。

**Comment by zijiren233** [comment]
下个版本将添加此功能和配置项。长时间不使用的房间自动从内存中删除（注意只是不加载到内存中，数据库中并不会删除），直到有用户加入房间才会加载到内存中而实现懒加载并节省内存
