### ISSUE TITLE
希望能添加一个不用验证的简单注册方式，而且分享链接是带密码的，望修复

### ISSUE THREAD

**Issue by sky22333** [synctv-org/synctv#167]
如题，国内环境接入第三方登录太麻烦了，如果怕别人恶意刷注册可以添加手动关闭这个简单注册功能，而且用户输入密码进入房间后分享链接是带密码的，游客用户有这个分享链接可以无需输入密码进入房间，希望修复一下，可以直接删掉房间分享功能，因为可以直接复制地址栏的链接分享

**Comment by zijiren233** [comment]
下个版本支持此功能

**Comment by zijiren233** [comment]
fix on [v0.7.0](https://github.com/synctv-org/synctv/releases/tag/v0.7.0)
