### ISSUE TITLE
[询问]请问作者大大，如何限制/开放房间的创建呢

### ISSUE THREAD

**Issue by Mydong** [synctv-org/synctv#17]
就如同demo的站点一样，网站的信息公开后。
会有很多测试的房间出来，很显得杂乱无章。
请问，站长如何限制，【暂时不开放/开放创建房间或者仅管理可创建】这种设置呢；

**Comment by zijiren233** [comment]
下个版本添加权限和设置界面

**Comment by Mydong** [comment]
> 下个版本添加权限和设置界面

太好了~ 感谢
