### ISSUE TITLE
[建议] 将"OAuth2 管理"左边的emoji换掉

### ISSUE THREAD

**Issue by LegendAdmin** [synctv-org/synctv#179]
理由如下：

1. 现在用的“法蒂玛之手” `🪬` 无论是形象还是含义上都并不贴切
2. **在常用的Win10系统中无法正常显示**
3. 有其它更合适的替代品，例如：`🔘` `🆔` `⭕️` 等

**Comment by zijiren233** [comment]
fix on [v0.7.0](https://github.com/synctv-org/synctv/releases/tag/v0.7.0)
