### ISSUE TITLE
无限重定向

### ISSUE THREAD

**Issue by huankong233** [synctv-org/synctv#19]
**Describe the bug**
无限重定向

**To Reproduce**
1.正常创建用户房间等
2.删除该用户存在的唯一一个房间
3.就会在该页面无限重定向

**Expected behavior**
回到首页或其他正确的处理方式

**Screenshots**
![image](https://github.com/synctv-org/synctv/assets/49610758/e2561c2d-4bc0-4ba6-96ef-3e5b09066bea)

**Desktop (please complete the following information):**
 - Browser latest chrome
 - Version latest docker version

**Comment by huankong233** [comment]
手动回到首页没问题

**Comment by zijiren233** [comment]
感谢反馈，已知bug，将在下个版本修复

**Comment by zijiren233** [comment]
已修复
