### ISSUE TITLE
添加影片时的自定义header似乎不起作用

### ISSUE THREAD

**Issue by Rean-Schwarze** [synctv-org/synctv#191]
**Describe the bug**
设置自定义header后，发出的请求没有带上自定义header

**To Reproduce**

**Expected behavior**
设置后带上自定义header发送请求

**Screenshots**
![image](https://github.com/synctv-org/synctv/assets/19246285/1a58765b-6a73-40e5-805b-70873bc7e5a0)
![image](https://github.com/synctv-org/synctv/assets/19246285/b82c7d31-b57f-4a24-8e73-492d44d88c9a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: v126

**Additional context**

**Comment by zijiren233** [comment]
有些header会被浏览器限制的，使用代理功能
