### ISSUE TITLE
希望房间设置实时更新

### ISSUE THREAD

**Issue by Kimaru-bili** [synctv-org/synctv#193]
希望房间设置能够实时更新 房主后台操作完用户刷新就会消失/增加权限 而非重启以后

**Comment by zijiren233** [comment]
操作完用户权限后，用户只需要刷新浏览器即可，不需要重启呀

**Comment by Kimaru-bili** [comment]
> 操作完用户权限后，用户只需要刷新浏览器即可，不需要重启呀

好像对访客用户不生效诶 我尝试用访客用户试了一下刷新浏览器 还是没生效🤔不知道是不是我用docker部署的问题

**Comment by zijiren233** [comment]
你改了哪个设置无法生效？

**Comment by Kimaru-bili** [comment]
> 你改了哪个设置无法生效？

访客的权限 用户的权限好像也是刷新不行🤔跟我在软路由上部署的有关系么(

**Comment by Kimaru-bili** [comment]
访客访问
![Screenshot_2024-06-22-20-08-27-834_com android chrome](https://github.com/synctv-org/synctv/assets/40233772/1e40ada1-ca9c-4df9-bf80-98f27cb02db5)
实际给访客权限
![Screenshot_2024-06-22-20-08-48-286_com android chrome](https://github.com/synctv-org/synctv/assets/40233772/b319457d-d1fd-4996-89b6-8c780b68e47f)

**Comment by Kimaru-bili** [comment]
我的搭建的网址(
v3.kimaru.cn:8995
大佬你可以进来试试(麻烦了

**Comment by zijiren233** [comment]
v0.6.6已修复

**Comment by Kimaru-bili** [comment]
> v0.6.6已修复

感谢大佬 大佬辛苦修Bug了 给你点个Star(

**Comment by Kimaru-bili** [comment]
> v0.6.6已修复

那个 用户权限好像也有这个问题😂麻烦了(

**Comment by zijiren233** [comment]
那个用户权限指的是用户默认权限，是用户首次加入房间用来初始化的，你要修改某个用户的权限需要到用户列表中修改

**Comment by Kimaru-bili** [comment]
> 那个用户权限指的是用户默认权限，是用户首次加入房间用来初始化的，你要修改某个用户的权限需要到用户列表中修改

OK明白了，感谢大佬指点(
