### ISSUE TITLE
在文件夹中添加大量影片翻页功能失效

### ISSUE THREAD

**Issue by liqman** [synctv-org/synctv#195]
创建文件夹后，在里面添加影片，翻页功能失效，显示全量影片，无法按条数显示每页数量；
由于文件夹中有大量影片，手机端（ios edge浏览器）在点击进入文件夹后，无法响应，电脑端正常显示，但是显示的是全量影片。

**Comment by KonoLLo** [comment]
AList添加影片同样有这个问题。分页功能失效
![微信截图_20240619181906](https://github.com/synctv-org/synctv/assets/74148088/b843b0db-56cc-4834-8aef-5293adf171fb)

**Comment by wujidaoren** [comment]
最好能加滚动条~~

**Comment by xingming-cainiao** [comment]
排序功能也没有，自动播放下一集

**Comment by zijiren233** [comment]
fix on [v0.7.0](https://github.com/synctv-org/synctv/releases/tag/v0.7.0)
