### ISSUE TITLE
[web播放器]播放问题

### ISSUE THREAD

**Issue by swRains** [synctv-org/synctv#2]
目前经过我的测试，目前的artplayer播放器只能放mp4格式，rmvb、avi、m3u8格式实测无法播放。
此外由alist提供的下载链接好像也无法播放，即便是用302跳转后的原链接也无法播放，我看alist上也用的artplayer可以正常播放，可能在设置上有些不同。
测试链接：
https://media.w3.org/2010/05/sintel/trailer.mp4

https://drivers.wegame.store/d/one/%E5%85%B6%E4%BB%96/test2.mp4

https://movie.wegame.store/test.avi

https://movie.wegame.store/test2.mp4

https://movie.wegame.store/test3.rmvb

https://cn-beijing-data.aliyundrive.net/ykczw3A5%2F63548212%2F640335941c53f50090a74a6fb727d00bcbc63ddd%2F64033594081c20ef1b374445b94d9161c64aa4bd?di=bj29&amp;dr=773525480&amp;f=651e2cc2f4c57ec646e049e5b8a1e6097178dc08&amp;response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27test2.mp4&amp;security-token=CAIS%2BgF1q6Ft5B2yfSjIr5DGMvH82etn1JaYb1DWgVdsfL5HqIifhTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVvVEFuPqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABZrTi2zCp2szu3iAaw8Y2bc%2BeqgXpy1RZMXdmlUntRp2n15V7kC3kdwd8X6cCwmkQmyPeIdpdNWjJXN%2F2A%2B6aVF6pTKIbzclCGEQzf19hBdObnjhujBCdz6xT5dJMaUnNTic6RjNvwGdvfcHQSo3zeXL%2BI%2BuK67SW4wMKufGuXpQgAA%3D%3D&amp;u=cda13c1c18474ed7812a11bb7bfe4c28&amp;x-oss-access-key-id=STS.NSsyKH44FcTsmvgeW9p1kGM4g&amp;x-oss-expires=1696490797&amp;x-oss-signature=%2BF8ga55nck4GvHDZbB%2BJZDcmah63qZaLDCD29QDI7lk%3D&amp;x-oss-signature-version=OSS2

**Comment by zijiren233** [comment]
m3u8已经可以播放了，avi和rmvb不适合当作流媒体播放，在浏览器播放非常困难，无法实现

**Comment by swRains** [comment]
> m3u8已经可以播放了，avi和rmvb不适合当作流媒体播放，在浏览器播放非常困难，无法实现

额那请问有没有办法播放阿里云盘的链接呢，其他网盘或者流媒体也行，现在我试了阿里云盘，超星，谷歌、B站下载链接均不行，只有那种纯文件链接，不带参数的才能播放比如cloudflare 的R2等对象存储才能放，那不还是相当于服务器提供上传嘛。
我看alist可以播放这些，您看能不能参考下呢，他也用的artplayer。

**Comment by zijiren233** [comment]
你可能指的是解析网盘视频？alist onedrive的视频的下载链接我测试过正常呀，目前这个项目只能播放视频直连，视频解析的功能以后会考虑

**Comment by swRains** [comment]
好的，是我唐突了，期待你的更新。我不懂前端，只会写脚本🙃

zijiren ***@***.***> 于 2023年10月10日周二 00:12写道：
