### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by ametoyuki098** [synctv-org/synctv#20]
safari浏览器和苹果上其他第三方浏览器不支持播放 手机版火狐有卡顿不流畅现象（可能是我手机硬件过低）

**Comment by zijiren233** [comment]
尝试0.3.0版本，应该safari可以播放了

**Comment by ametoyuki098** [comment]
版本0.3.0a-3 没法创建房间 登录界面是不是还有什么没显示出来。

![image](https://github.com/synctv-org/synctv/assets/109204477/ea73878e-0957-46f8-9dd5-5b322e37feff)

**Comment by zijiren233** [comment]
0.3.0-beta-1已修复
