### ISSUE TITLE
快进会导致重放

### ISSUE THREAD

**Issue by tuimao615** [synctv-org/synctv#201]
我使用的是alist里链接的阿里云盘open的播放链接，每次使用倍速播放大概15分钟视频就会回到开头重新播放，并且暂停时房间其他观影不会暂停而是在暂停处前后几秒来回重复播放

**Comment by KonoLLo** [comment]
这是阿里云盘的问题，最大连接时间为15分钟。解决方法是自己申请成为阿里云盘开发者使用自己的api挂载alist。或者换网盘
