### ISSUE TITLE
请问能不能让访客看不见房间列表

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [synctv-org/synctv#202]
请问能不能让访客看不见房间列表，我自己没找到设置，如果没有请问能否添加这个这个功能，感谢

**Comment by Watercolor-tone** [comment]
进房间，房间设置，隐藏房间

**Comment by SchrodingerBarbatos** [comment]
> 进房间，房间设置，隐藏房间

我的想法是访客可以设置成无权限的，不然按您这样设置的话，用户登陆了就看不见房间了
