### ISSUE TITLE
经常会出现webscoket重连失败

### ISSUE THREAD

**Issue by carlzhu0609** [synctv-org/synctv#203]
明明正在观看，房间会自动处于CLOSE，然后会一直提示websocket重连失败，这个是什么原因呢？

**Comment by Suuperfishy** [comment]
我发现我的容器只要重启过也会这样

**Comment by zijiren233** [comment]
反向代理的问题

**Comment by PhDLuffy** [comment]
@zijiren233 大佬您好，请问下这个反向代理是否与wss有关？

我只用了frp做反向代理，

在tcp下没有问题，但是只能http，无法使用语音。

在https下，就会出现不断connecting，closed之间切换，此时语音可以打开，但是没有声音。
