### ISSUE TITLE
无法播放emby视频

### ISSUE THREAD

**Issue by jacky940810** [synctv-org/synctv#209]
**Describe the bug**
使用平台绑定emby后在房间内选择影片列表并点击播放，会提示加载失败，通过抓包发现Request URL中缺少api_key，
requestrul表现为：
http://www.XXX.XXX:2345/emby/videos/1606764/stream.mkv?reqformat=json&api_key=_embyApiKey&MediaSourceId=403267141cd0bd1ab302ff4202cc55aa&PlaySessionId=c5e17bba82a346ceb97a617cf9906993&Static=true
**To Reproduce**
点击平台绑定输入emby网址、账号、密码（网站为ipv6ddns，无ipv4公网ip）
进入房间
添加影片
选择emby
添加收藏夹
选择影片并点击播放
提示设置成功，观察浏览器network出现401报错：
Access token is invalid or expired.

**Expected behavior**
请求头api_key=_embyApiKey中_embyApiKey应为emby的apikey，而非预设值

**Screenshots**
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/1cbe97ca-2166-4835-9e0f-bd1233b1a622">

**Desktop (please complete the following information):**
最新的docker

**Smartphone (please complete the following information):**

**Additional context**
请修复

**Comment by zijiren233** [comment]
不应该啊，这个apikey不是拼接上去的，是获取播放地址的api返回的

**Comment by jacky940810** [comment]
检查了一下前一个api的返回值存在错误,返回的 "movie"的"url"为
"http://www.xxx.xxx:2345/emby/videos/785983/stream.strm?reqformat=json\u0026api_key=_embyApiKey\u0026MediaSourceId=132733efb27390793900d9a6a4a4e60f\u0026PlaySessionId=589af6fecefe4909b0d5de0aedd9ff77\u0026Static=true",
                "name": "纪录片",

**Comment by jacky940810** [comment]
经过G大指点在xiaoya中添加infuse_api_key.txt，内容为emby的api-key，成功解决问题
