### ISSUE TITLE
局域网使用的情况下注册会很麻烦，希望有简单注册功能不用验证

### ISSUE THREAD

**Issue by Rod-fish** [synctv-org/synctv#214]
如图，我家三层的都挤一起看很麻烦所以搭了这个，但是局域网下面也不需要那么麻烦的注册只需要获取用户名就行了
现在的注册是必须oauth2或者走邮件，但是我看了下没有不验证的注册办法，只能默认开全部访问模式或者root用户一个个开账号拉权限就很麻烦

**Comment by zijiren233** [comment]
注册问题短期内不会调整
