### ISSUE TITLE
房间设置-不能正确的设置权限

### ISSUE THREAD

**Issue by Qyinfu** [synctv-org/synctv#215]
房间设置修改后，只有最后一个修改项可以被应用。mysql数据库实际存储的是所有修改项，/api/room/admin/settings 返回的却是最后一个修改项。
![image](https://github.com/user-attachments/assets/b01342e5-d674-4fa6-a100-c88daf4dce73)
![image](https://github.com/user-attachments/assets/57f606c9-6801-45d5-9f66-b6b8059dfdd4)

这是我的部署脚本
`
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./nginx/alist.conf
        target: /etc/nginx/conf.d/alist.conf
        read_only: true
      - type: bind
        source: ./nginx/http.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./ssl/
        target: /etc/nginx/ssl
        read_only: true
    ports:
      - "2096:2096"
      - "8443:8443"
    depends_on:
      - mysql
      - synctv
      - alist

  mysql:
    image: mysql:8
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/mysql-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - mysql-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=synctv
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-password
    expose:
      - 3306

  synctv:
    image: "synctvorg/synctv:0.6.9-beta.1"
    container_name: synctv
    restart: always
    expose:
      - 8080
    secrets:
      - mysql-password
    volumes:
      - synctv-data:/root/.synctv
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=synctv
    depends_on:
      - mysql

  alist:
    image: 'xhofe/alist:latest'
    container_name: alist
    volumes:
        - alist-data:/opt/alist/data
        - F:\video:/data
    environment:
        - PUID=0
        - PGID=0
        - UMASK=022
    restart: always
    ports:
      - "5244:5244"
    expose:
      - 5244

volumes:
  db-data:
  alist-data:
  synctv-data:

secrets:
  mysql-password:
    file: ./mysql/password.txt
`

**Comment by Qyinfu** [comment]
![image](https://github.com/user-attachments/assets/6b34c27b-7b36-4c88-a02c-ba08117d0872)
![image](https://github.com/user-attachments/assets/1e3a67d1-b884-4ad8-91b7-5bbc5c0c2293)

**Comment by zijiren233** [comment]
无法复现
