### ISSUE TITLE
obs无法连接服务器

### ISSUE THREAD

**Issue by linux-8** [synctv-org/synctv#219]
docker run -d --name synctv -p 8080:8080 --restart=always synctvorg/synctv

推流码：rtmp://d.1234.ist/03523cbc3997489eb8193902983d006d/   （正常的话是有端口号的8080）

反向代理：
location / {
        proxy_pass http://localhost:8080;
        proxy_cache off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Range $http_range;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header If-Range $http_if_range;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 200m;
        }

请问哪里出问题了，请大神指点
![00974b19eff0d1052a134db60788dbc](https://github.com/user-attachments/assets/893eb440-18cc-431b-9f6a-d829d3848c4f)

**Comment by zijiren233** [comment]
rtmp不是http协议，不能使用nginx反向代理http协议到rtmp
你需要在设置中设置rtmp的host为ip:port或者domain:port
