### ISSUE TITLE
想问一下前端页面

### ISSUE THREAD

**Issue by 1378056564** [synctv-org/synctv#22]
您好，我是通过全部代码进行部署的，已经成功运行了
但是我好奇，它的/web/页面来源于哪里
是直接拉取大佬您的另一个前端项目吗？ synctv-org/synctv-web吗
还是说构建出来或者说已经包含在synctv这个项目里面了
包含的话想知道一下具体路径
已经public/dist里面并没有看到有/web

**Comment by zijiren233** [comment]
release中已经打包了前端代码到服务端了，只需要把前端构建文件放到dist中然后构建后端即可

**Comment by 1378056564** [comment]
> release中已经打包了前端代码到服务端了，只需要把前端构建文件放到dist中然后构建后端即可

emmm，我直接下载的0.2.4，然后用server就跑起来了，但是public/dist里面就只有.gitkeeep   如果我自己同时下载了您的synctv/web项目，并且想用这个/web的项目作为前端然后0.2.4这个作为后端。我应该怎么在root/.config/synctv/config.yaml里面设置呢，或者这个0.2.4包含的前端页面在哪里。
实在是找不到0.0打开来也直接显示7980的端口，以及域名/web/这样。。。但是端口却又没有被占用

**Comment by zijiren233** [comment]
你可以看看[构建脚本](https://github.com/synctv-org/synctv/blob/main/build.sh#L128)，必须要把前端的构建文件放到dist里面，然后编译后端的时候就会自动把前端文件打包到后端二进制文件里面
