### ISSUE TITLE
希望增加权限管理功能

### ISSUE THREAD

**Issue by XiangJiang-Wang** [synctv-org/synctv#23]
如题，可以开启注册审核（注册字段可以自定义），仅管理员可以创建房间，房间支持设置权限：开放时间，登录访问，密码访问，互动审核，直播预约。房间标题，房间简介，如此可用于教学场景的常态化中直播间，现在很多学校在教室都有安装摄像头，但是欠缺一套合适的直播平台，商业化的CDN分发网络成本很高，可以利用此项目在校园网自建常态化直播间，用于线上教学。

**Comment by zijiren233** [comment]
大部分权限已经实现
