### ISSUE TITLE
视频播放只有画面没有声音

### ISSUE THREAD

**Issue by Passerby1011** [synctv-org/synctv#238]
**Describe the bug**
视频播放时只有画面没有声音，视频在本地播放时是有声音的，使用有的形式是onedriver的直链进行播放，视频本体：
汉尼拔.S01
https://www.alipan.com/s/7fEhQcuuKa2
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
**To Reproduce**
1. 把视频上传到onedriver上
2.想办法生成视频的直链
3.把视频直链添加进synctv进行播放
4.视频正常播放但是没有声音

**Expected behavior**
视频正常播放，有声音，

**Screenshots**
![image](https://github.com/user-attachments/assets/cb22e62a-36e6-4144-8cff-35ece70df947)

**Desktop (please complete the following information):**
 - win11
 - yandex

**Smartphone (please complete the following information):**

**Additional context**
更换使用edge也没有声音

**Comment by zijiren233** [comment]
浏览器支持的视频编码有限
