### ISSUE TITLE
能修改播放器的字幕偏移设置吗？

### ISSUE THREAD

**Issue by skyline-2b** [synctv-org/synctv#239]
![Snipaste_2024-10-03_16-51-51](https://github.com/user-attachments/assets/c1a60c8c-4068-4c46-8007-1a4860667077)
现在的字母偏移选项，只能够让字幕更早的出现，并且只有0，1，2s，做不到细微的调整，希望能改成图二这种模式，或者我有什么办法能自己修改这个选项吗？
![Snipaste_2024-10-03_16-56-10](https://github.com/user-attachments/assets/36fe7632-e929-4dc3-ba89-2680ad7edd9b)

**Comment by zijiren233** [comment]
fix on [v0.7.0](https://github.com/synctv-org/synctv/releases/tag/v0.7.0)
