### ISSUE TITLE
可不可以加个语音开关，开启后可以在一起看的时候聊天

### ISSUE THREAD

**Issue by Mark-li521** [synctv-org/synctv#251]
目前只有文字，极需一个可以互相说话的功能

**Comment by nanqic** [comment]
+1 要是能集成yy语音聊天就好了，边看边交流

**Comment by Mark-li521** [comment]
> +1 要是能集成yy语音聊天就好了，边看边交流

是的 现在要一边微信一边看直播

**Comment by sjw015** [comment]
是的！非常需要！如果有了实时语音交流就非常完美了！不知道为啥synctv自带的rmtp直播推流总是用不了，但是在vlc等播放器是没问题的。如果有了实时语音交流那也相当于直播了，不用再搞rmtp推流了。

**Comment by shenjiawang** [comment]
已经有语音功能！完美啊！再也不用因为版权问题和无人直播问题被平台封禁啦！！！

**Comment by zijiren233** [comment]
v0.9.0已经支持语音
