### ISSUE TITLE
访客加入房间提示请先登录

### ISSUE THREAD

**Issue by Nguyendream** [synctv-org/synctv#253]
**Describe the bug**

version: 0.7.0-0.7.9
访客身份，加入房间时提示需要登陆
设置不做修改，退回0.6.9正常

**Additional context**
补充一个额外发现，点击`首页`与`房间列表`，查询接口会调用2次，而点击`更新列表`只会调用一次。

**Comment by zijiren233** [comment]
最新版中访客无法加入到具有密码的房间中，这是为了简化token数量与复杂度。
