### ISSUE TITLE
能否跟alist一样解决阿里云播放19分钟固定卡顿的问题

### ISSUE THREAD

**Issue by skyline-2b** [synctv-org/synctv#257]
alist: v3.37.4
syncTV: v0.7.9

我将synctv和alist都安装在了我租赁的服务器上，先由alist挂载了我的阿里云盘open，再将资源放到synctv上播放。我发现在播放途中，如果视频源文件较大的话，在播放到18：59时，synctv的播放页面会一直转圈卡顿，需要刷新页面才能重新播放。我试过在alist上观看同一个视频文件，alist本身在18：59时也会卡顿，但它似乎会重新获取视频流，只需要等待几秒就能继续播放。
希望synctv可以也像alist一样尝试重新获取视频流，以下是alist的解决方案：https://github.com/msterzhang/onelist/issues/84

**Comment by skyline-2b** [comment]
PS：发现是Aliyun Video Previewer观看时才会有这个问题，源切换成raw就没问题了，但还是希望能有个“刷新键”之类的，有的视频看raw会黑屏

**Comment by zijiren233** [comment]
alist 阿里的视频应该会在14分钟自动刷新呀

**Comment by skyline-2b** [comment]
我记得几个月前还是15分钟的，最近变成19分钟了，不过我现在也解决了看raw会黑屏的问题（原来是缺少hevc解码的问题），还是不用麻烦你们了哈哈
