### ISSUE TITLE
大佬能不能增加一个本地视频播放的功能

### ISSUE THREAD

**Issue by guogegod** [synctv-org/synctv#26]
大佬能不能增加一个本地视频播放的功能，现在是只能使用双方都能访问到的资源才能播放吗？

**Comment by muziqiu2** [comment]
> 大佬能不能增加一个本地视频播放的功能，现在是只能使用双方都能访问到的资源才能播放吗？

播放本地视频肯定得需要双方都有的

**Comment by zijiren233** [comment]
如果本地视频和服务器在同一网段，可以使用视频代理功能来实现你的需求

**Comment by Love-TNT** [comment]
用alist挂本地服务器再用synctv挂alist就行了
