### ISSUE TITLE
大电影播放失败

### ISSUE THREAD

**Issue by Ruoke321** [synctv-org/synctv#260]
**Describe the bug**
在播放长一点的大电影，例如白蛇3的时候，只有夸克浏览器能播放加载出来，其他的火狐，edge等都无法加载出来，之后我尝试了降低码率和切片m3u8等多种方式，均是如此

**Comment by Ruoke321** [comment]
转为m3u8以后会提示无法解码，mp4的话加载很慢甚至加载不出来，视频都是AVC(H264)编码的

**Comment by Ruoke321** [comment]
![Uploading IMG_20241116_213144.jpg…]()

**Comment by zijiren233** [comment]
这是浏览器视频解码的问题，没办法修，除非脱离浏览器开发原生软件
