### ISSUE TITLE
链接S3下载影片到本地之后，没有办法打开本地文件夹

### ISSUE THREAD

**Issue by DiLiuNEUexpresscompany** [synctv-org/synctv#264]
想咨询一下，我连接了s3之后，下载影片到本地Downloads文件夹，想要添加文件到syntv中，但是找不到文件，是不是需要Alist来中转一下

![image](https://github.com/user-attachments/assets/2bf9b548-4fbb-4f22-adcd-0d3c0d4c14e5)
![image](https://github.com/user-attachments/assets/16e83cef-adda-4f79-82ff-f9bb74337e6f)

**Comment by zijiren233** [comment]
对，需要使用alist，synctv无法读取文件夹，这个文件夹只是虚拟的文件夹
