### ISSUE TITLE
文档中的数据库配置与代码描述不一致

### ISSUE THREAD

**Issue by imHansiy** [synctv-org/synctv#265]
在文档中描述：
[db_name](https://docs.synctv.wiki/#/zh-cn/configuration?id=db_name)
类型: string
默认值: synctv
可选值: sqlite3 时可设置为 memory
环境变量: DATABASE_DB_NAME
当 type 为 sqlite3 时，该值为数据库文件路径，如果路径为相对路径，则相对于 data-dir。 如果 type 为 mysql 或 postgres 时，该值为数据库名。
环境变量名称为：
DATABASE_DB_NAME
在实际的代码中读取环境变量为：
Name     string       `env:"DATABASE_NAME"     hc:"when type is sqlite3, it will use sqlite db file or memory"                                            lc:"default: synctv"  yaml:"name"`
环境变量为：
DATABASE_NAME

**Comment by zijiren233** [comment]
已修复
