### ISSUE TITLE
Alist 部署在内网，使用IPV6穿透，但是挂载的时候IPV6地址无法解析

### ISSUE THREAD

**Issue by CaoJingBiao** [synctv-org/synctv#266]
Alist 部署在内网，使用域名 DDNS IPV6穿透，但是挂载Alist的时候IPV6地址无法链接

**Comment by 2beetle** [comment]
> Alist 部署在内网，使用域名 DDNS IPV6穿透，但是挂载Alist的时候IPV6地址无法链接

会不会是你部署的地方不支持ipv6

**Comment by zijiren233** [comment]
docker部署的吗？docker模式是没有ipv6的，尝试开启host网络模式或者启用docker ipv6功能
