### ISSUE TITLE
密码重置问题

### ISSUE THREAD

**Issue by bugroom** [synctv-org/synctv#267]
好久没启动这个项目了（docker部署的），今天突然想起，但当时设置的root用户密码忘记了，大佬怎么重置或者找回？还是说只能重新安装项目？

**Comment by zijiren233** [comment]
可以使用synctv命令重制

**Comment by bugroom** [comment]
> 可以使用synctv命令重制

麻烦大佬了，请下具体是哪条命令，蟹蟹

**Comment by zijiren233** [comment]
运行synctv命令有提示的，根据提示来

**Comment by bugroom** [comment]
> 运行synctv命令有提示的，根据提示来

这个synctv命令没有详细使用文档？

**Comment by bugroom** [comment]
> 好久没启动这个项目了（docker部署的），今天突然想起，但当时设置的root用户密码忘记了，大佬怎么重置或者找回？还是说只能重新安装项目？

已解决：

1.容器终端输入(会输出一个ID)：synctv root show

2.继续输入：synctv root remove ID
 这条移除命令后面需要加ID是真的提示不明显，在这卡了好久才想到可能需要ID

3.容器日志查看新生成的root账号和密码：
               username：root#数字
               password：root

4.看情况决定是否重启容器
