### ISSUE TITLE
[询问]OBS推流，连接不上

### ISSUE THREAD

**Issue by xM3GAN** [synctv-org/synctv#27]
![image](https://github.com/synctv-org/synctv/assets/80143495/f3e036ff-22c8-4978-b6c4-67c1f140f2a5)
![image](https://github.com/synctv-org/synctv/assets/80143495/4496a33f-bff3-42b2-b30a-139595942f66)
使用的是演示网站操作的，请问是我哪里操作错了吗，还是其他问题
flv格式，m3u8都尝试了

**Comment by zijiren233** [comment]
demo的推流地址的问题，因为开启了cdn所以连不上服务器

M三GAN ***@***.***> 于 2023年11月9日周四 16:59写道：
