### ISSUE TITLE
手动编译的如何简化命令行里的输出

### ISSUE THREAD

**Issue by TNT-Love** [synctv-org/synctv#271]
将图一简化成图二那样
![1](https://github.com/user-attachments/assets/52fc82f2-5575-4632-94e2-465417125a82)

![2](https://github.com/user-attachments/assets/74005f1e-8894-4a96-89d0-71a7f77b05a2)

**Comment by zijiren233** [comment]
手动编译默认为dev模式，具体编译命令可以参考
https://github.com/synctv-org/synctv/actions/runs/12309345829/job/34356209776#step:5:62

**Comment by Love-TNT** [comment]
呃呃我是在实体机用go编译的哇
