### ISSUE TITLE
docker启动登陆页面没有显示选项

### ISSUE THREAD

**Issue by sailaoda** [synctv-org/synctv#28]
**Describe the bug**
您好，我的问题是 利用 docker 拉取启动服务后，登陆页面未显示登录选项的情况。docker命令按照 文档 和 docker hub 进行输入。

我分别在 mac IOS 本地 和 服务器 Ubuntu 22.0 做了docker启动服务，都没有出现，如下图所示：

<img width="1161" alt="image" src="https://github.com/synctv-org/synctv/assets/44259537/ae23cafe-fe84-43ed-a250-2141c662d707">

请问您有遇到类似问题或者知道如何解决吗

**Comment by zijiren233** [comment]
登录方式需要在配置文件中自行配置，参考文档：https://synctv.wiki/#/zh-cn/oauth2-github

**Comment by sailaoda** [comment]
好滴，感谢！

**Comment by Mydong** [comment]
> 登录方式需要在配置文件中自行配置，参考文档：https://synctv.wiki/#/zh-cn/oauth2-github

原来在这个地方，我昨天晚上找了好久。
我说咋一直是空白的页面呢
