### ISSUE TITLE
请问能否发布支持armv7l-32的版本呢？

### ISSUE THREAD

**Issue by ErDongChen1973** [synctv-org/synctv#29]
如题，目前我在armv7l-32 ubuntu系统运行会发生如下错误：
panic: unaligned 64-bit atomic operation

goroutine 26 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x22f330c, 0x1)
        runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/zijiren233/gencontainer/rwmap.(*RWMap[...]).LoadOrStore.func1()
        github.com/zijiren233/gencontainer@v0.0.0-20231108115721-8d4bb333a5bc/rwmap/rwmap.go:207 +0x44
github.com/zijiren233/gencontainer/rwmap.(*RWMap[...]).LoadOrStore(0x1842988, 0x1, 0x4916810)
        github.com/zijiren233/gencontainer@v0.0.0-20231108115721-8d4bb333a5bc/rwmap/rwmap.go:241 +0x41c
github.com/synctv-org/synctv/internal/sysNotify.(*SysNotify).RegisterSysNotifyTask(0x22f32e8, 0x0, 0x49167f0)
        github.com/synctv-org/synctv/internal/sysNotify/sysNotify.go:89 +0x118
github.com/synctv-org/synctv/internal/sysNotify.RegisterSysNotifyTask(...)
        github.com/synctv-org/synctv/internal/sysNotify/sysNotify.go:23
github.com/synctv-org/synctv/internal/bootstrap.InitCheckUpdate.func1()
        github.com/synctv-org/synctv/internal/bootstrap/update.go:39 +0x3fc
created by github.com/synctv-org/synctv/internal/bootstrap.InitCheckUpdate in goroutine 1
        github.com/synctv-org/synctv/internal/bootstrap/update.go:18 +0xfc

**Comment by zijiren233** [comment]
已修复
