### ISSUE TITLE
不能正常使用的bug报告和相关建议

### ISSUE THREAD

**Issue by zbuhui** [synctv-org/synctv#34]
部署环境: 群晖6.2 docker部署,
使用环境: chrome浏览器 版本 119.0.6045.160（正式版本） （64 位）,火狐浏览器版本: 109.0.1 (64 位)
视频源: alist挂载的阿里云盘的视频直链
1, 用户管理方面: 每次加入不同房间都需要登录, 页面没有展示用户状态
建议:分2人使用和多人使用场景,2人使用匿名即可,多人使用才需要登录
2. 播放mkv视频有图像没声音
3.  影片列表有多个时,正在播放视频1时直接点视频2的播放,不会切换,然后我刷新网页点'影厅'是切换到视频2了,但是这时候房间连接状态变closed;视频界面左上角重新连接5次失败后显示'加载失败',中间弹框'Websocket 自动重连失败！',
本地换别的账号,异地,异地换账号,换火狐浏览器 都是同样报错,; 
4. 有时正常播放也会有中间弹框'Websocket 自动重连失败！',
5. 重启容器后配置的房间信息和播放列表丢失.貌似回退到初始状态

**Comment by zijiren233** [comment]
最新版已修复
