### ISSUE TITLE
user用户组权限太大了

### ISSUE THREAD

**Issue by vivafriend** [synctv-org/synctv#37]
辛辛苦苦创建的链接 其它用户进来全删除了  
创建房间应该增加设置是否允许其它用户 增 删 编辑
甚至 是否允许显示视频链接地址。

是不是开通默认游客可以直接访问，不用登录。

🥲

**Comment by zijiren233** [comment]
在v0.3.0中，应该不会出现创建的链接被其它普通用户删除，你可以到 [demo](https://demo.synctv.wiki) 试试能否删除测试房间内的视频。
除非用户是管理员，不然是没有权限删除其它用户创建的视频的。
