### ISSUE TITLE
通过矿神套件升级到0.3.0之后没有配置OAuth的入口

### ISSUE THREAD

**Issue by PartialC** [synctv-org/synctv#38]
通过矿神套件升级到0.3.0之后没有配置OAuth的入口，也没有用户注册入口。

**Comment by zijiren233** [comment]
用户注册是自动化的，当你配置了oauth后通过oauth登录会自动注册
oauth配置在登录管理账号后进入管理界面的oauth2管理中设置

**Comment by PartialC** [comment]
问题解决了，原来是没登录管理员账号！
谢谢！




萧声咽.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "synctv-org/synctv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月1日(星期五) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [synctv-org/synctv] 通过矿神套件升级到0.3.0之后没有配置OAuth的入口 (Issue #38)





 
用户注册是自动化的，当你配置了oauth后通过oauth登录会自动注册
 oauth配置在登录管理账号后进入管理界面的oauth2管理中设置

**Comment by a312354805** [comment]
不配置oauth2应该怎么自动注册呢

**Comment by PartialC** [comment]
> 不配置oauth2应该怎么自动注册呢

好像操作不了，我是直接root后台添加新账号的
