### ISSUE TITLE
iphone的浏览器没法播放

### ISSUE THREAD

**Issue by xiaochenchui** [synctv-org/synctv#42]
播放的alist的直链，电脑正常，安卓手机浏览器正常，iphone的浏览器播放不了

**Comment by PartialC** [comment]
![QQ图片20240101181052](https://github.com/synctv-org/synctv/assets/52561433/b932597e-4a53-4d4d-99b3-e9cab062ce22)
遇到类似的问题，Alist直链可以播放，但是直播推流一直显示加载中。
同一条宽带下的电脑浏览器播放正常，安卓手机浏览器播放正常。

**Comment by PartialC** [comment]
IOS更换Edge浏览器也是显示加载中

**Comment by zijiren233** [comment]
已修复

**Comment by FutureUnreal** [comment]
> 已修复
在ios emby播放不了也是一样的问题吗
