### ISSUE TITLE
请求增加jellyfin的支持

### ISSUE THREAD

**Issue by moehz** [synctv-org/synctv#50]
**Is your feature request related to a problem? Please describe.**
不是

**Describe the solution you'd like**
目前已经支持了emby,我使用jellyfin的账户密码能够登陆，不过工作不正常，希望增加关联jellyfin的选项

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zijiren233** [comment]
由于我没有jellyfin服务器所以没法测试

**Comment by moehz** [comment]
> 由于我没有jellyfin服务器所以没法测试

你好，可否留一个邮箱，我可以给您发一个jellyfin的地址和测试账号

**Comment by zijiren233** [comment]
[email](mailto:pyh1670605849@gmail.com)

**Comment by moehz** [comment]
> [email](mailto:pyh1670605849@gmail.com)

好的，已经给您发了

**Comment by yuanshi76** [comment]
+1

**Comment by Neptune1990** [comment]
+1

**Comment by Chikage0o0** [comment]
+1

**Comment by huai0826** [comment]
你好，08/27添加jellyfin实测，可以使用emby登录，在房间也可以在正常获取文件列表，但点击播放后，提示报错：
获取影片列表失败
gen current movie info error: playback info: status code 400: {"type":"https://tools.ietf.org/html/rfc9110#section-15.5.1","title":"One or more validation errors occurred.","status":400,"errors":{"$.DeviceProfile.CodecProfiles[0].Conditions[0].IsRequired":["The JSON value could not be converted to System.Boolean. Path: $.DeviceProfile.CodecProfiles[0].Conditions[0].IsRequired | LineNumber: 0 | BytePositionInLine: 949."]},"traceId":"00-2a6201a2e505359db14116bd73047711-5a087a8cf7d6d036-00"}

![bfb9d4c4-a057-4517-b3f5-e70b92a9b525](https://github.com/user-attachments/assets/7b92062b-ec73-446d-b670-ed06ac12175b)

希望这条留言可以看到，感谢大佬！

**Comment by eerroorr** [comment]
与楼上同样的问题，同求 jellyfin 的支持

**Comment by moehz** [comment]
我已经不怎么用了，如有相同需求的人请重新提单
