### ISSUE TITLE
如何连接alist呀？找不到设置有地方配置呢

### ISSUE THREAD

**Issue by grey-337** [synctv-org/synctv#51]
<img width="405" alt="image" src="https://github.com/synctv-org/synctv/assets/127077523/70426d1b-7db6-4532-bbad-35bb2a152220">
<img width="875" alt="image" src="https://github.com/synctv-org/synctv/assets/127077523/27a8b193-ad1f-4fbd-b656-bccdf4a8173a">

**Comment by zijiren233** [comment]
个人信息界面里面有绑定的地方

**Comment by grey-337** [comment]
卧槽，谢谢！找到了

**Comment by grey-337** [comment]
我一直以为这是个系统级别的配置，原来是个人级别的配置

**Comment by oneisall8955** [comment]
建议将该配置写在 wiki 文档里面，或为空的时候，提示引导用户到个人账号信息界面绑定
