### ISSUE TITLE
IPhone上无法观看直播

### ISSUE THREAD

**Issue by FuDujilm** [synctv-org/synctv#60]
**Describe the bug**
在IOS17.3上，我不能观看我自己推流的直播，浏览器为Edge
![aaed9a9fbc7d253c00f524923f2c98da](https://github.com/synctv-org/synctv/assets/72288165/a78222a8-c362-4874-a541-87e80a62da73)

图像中提示不支持的格式，flv,尝试过m3u8也无法播放

**Comment by Molu1127-15** [comment]
我是iOS17.2.2，我用手机观看Alist的视频也提示格式错误。浏览器为Safari。Windows上使用Google Chrome可以正常播放。

**Comment by songyp0505** [comment]
同样存在上述两个问题🙋

**Comment by zijiren233** [comment]
貌似ios不支持flv的拉流

**Comment by lushuaihui** [comment]
貌似苹果设备 看alist很多都不支持，望作者尽快更新

**Comment by zijiren233** [comment]
v0.3.5已经修复hls播放问题，flv应该无论如何也不能在ios上播放

**Comment by songyp0505** [comment]
那应该怎么做呢，用alist的时候好像也不能指定格式，ios上无解嘛。。

**Comment by zijiren233** [comment]
> 那应该怎么做呢，用alist的时候好像也不能指定格式，ios上无解嘛。。

已经修复，不过只能用m3u8播放
