### ISSUE TITLE
搭配alist使用，看不了10分钟就会停止，并提示获取影片列表失败path is invalid

### ISSUE THREAD

**Issue by qq77522980** [synctv-org/synctv#64]
如题，看一会儿视频就会停止，刷新就提示这个，基本没办法正常使用。
![17055020012103380527690116185779](https://github.com/synctv-org/synctv/assets/74188271/37da17a4-bfe3-4df0-8aef-44b5776cc3d0)

**Comment by zzj2039** [comment]
+1

**Comment by oldliumark** [comment]
+1

**Comment by MySunbing** [comment]
+1，我目前使用的方法是添加alist直链。

**Comment by qq77522980** [comment]
> +1，我目前使用的方法是添加alist直链。

直链能解决问题吗，我仿佛试过一次也会断。

**Comment by zijiren233** [comment]
已修复
