### ISSUE TITLE
播放问题

### ISSUE THREAD

**Issue by zzj2039** [synctv-org/synctv#66]
视频在播放过程中，一旦有人进入房间或者刷新页面，就会导致视频进度被重置，所有人从头开始看
已测试：
手机端Chrome 版本 120.0.6099.144 问题存在
手机端Edge 版本 120.0.2210.99 问题存在
手机端Edge 版本 120.0.2210.115 问题存在
手机端Via 版本 5.2.0 问题不存在

**Comment by zzj2039** [comment]
补充：
在demo网站中同样有这个问题

**Comment by zzj2039** [comment]
又测试了下 电脑没有这个问题，但是手机用户进入房间会导致重置进度

**Comment by zijiren233** [comment]
已修复
