### ISSUE TITLE
勾选允许使用 RTMP 播放器后，rtmp链接在哪？怎样使用VLC播放？ 

### ISSUE THREAD

**Issue by muvn** [synctv-org/synctv#71]
勾选允许使用 RTMP 播放器，如何使用VLC播放？
可以这样使用吗？吧VLC当作synctv的客户端进行播放。在网页内添加视频和调整播放进度。
我这里测试添加播放列表后无法自动播放下一个视频。

**Comment by zijiren233** [comment]
rtmp推流地址后面拼接一个movie id就是拉流地址，只不过前端目前没做自动显示拉流地址的功能，因为这个功能无法同步切换视频、进度，仅仅只是播放此直播的视频

**Comment by zijiren233** [comment]
安卓app不会啊QAQ
