### ISSUE TITLE
是否可以添加外挂音频

### ISSUE THREAD

**Issue by zuijiaoshangyang2** [synctv-org/synctv#72]
是否可以添加选择配音功能

**Comment by zijiren233** [comment]
外挂音频？这个有什么用途吗？

**Comment by zuijiaoshangyang2** [comment]
对不起，我想表达的是类似emby奈飞一样的选择配音，因为有些电影提供了多个配音，默认的不是最想要的。而且我使用这个软件播放emby里一些有多配音的电影时没有声音。

**Comment by zijiren233** [comment]
这不是外挂音频，emby是用的mkv内敛音频，奈飞是通过mpd实现的多音频
暂时emby还没适配多音频的版本，以后可能会适配

**Comment by zuijiaoshangyang2** [comment]
> 这不是外挂音频，emby是用的mkv内敛音频，奈飞是通过mpd实现的多音频 暂时emby还没适配多音频的版本，以后可能会适配

不好意思是我搞错了，感谢你的科普，很高兴听到你说以后会适配。

**Comment by zuijiaoshangyang2** [comment]
还有一个问题是为什么有些从emby获取的视频无论在安卓网页端还是pc网页端都没有声音，似乎aac解编码器的配音音频都是正常的，其他的解编码器音频会没有声音。
