### ISSUE TITLE
b站的番剧、电视剧、电影添加失败

### ISSUE THREAD

**Issue by album-GitHub** [synctv-org/synctv#73]
选中视频后添加提示Request failed with status code 400
普通视频可以正常添加

**Comment by zijiren233** [comment]
我测试没有问题呀，能在f12控制台看看api返回的具体的错误内容是什么吗？

**Comment by album-GitHub** [comment]
> 我测试没有问题呀，能在f12控制台看看api返回的具体的错误内容是什么吗？

错误信息如下：
POST https://域名+端口/api/movie/pushs 400 (Bad Request)
XMLHttpRequest.send @ inspector.js:7
（匿名） @ index-b6fad90b.js:11
xhr @ index-b6fad90b.js:11
Xa @ index-b6fad90b.js:13
request @ index-b6fad90b.js:13
（匿名） @ index-b6fad90b.js:9
J3 @ index-b6fad90b.js:14
Z3.u3.immediate @ index-b6fad90b.js:14
p @ index-b6fad90b.js:13
execute @ index-b6fad90b.js:14
x @ Cinema-fcc78dfc.js:37
u.value.length.createElementBlock.onClick.C.<computed>.C.<computed> @ Cinema-fcc78dfc.js:37
Ft @ index-b6fad90b.js:1
Je @ index-b6fad90b.js:1
n @ index-b6fad90b.js:1
![image](https://github.com/synctv-org/synctv/assets/51018113/9bf37d02-be53-4716-841f-8a1755b04772)
添加时这两个勾也是没法勾选的

**Comment by zijiren233** [comment]
应该到网络控制台，看看api返回的具体报错信息

**Comment by album-GitHub** [comment]
> 应该到网络控制台，看看api返回的具体报错信息

![image](https://github.com/synctv-org/synctv/assets/51018113/8bc8a523-a301-4dd7-946e-fc7ed140db3a)
是这里么？

**Comment by album-GitHub** [comment]
> > 应该到网络控制台，看看api返回的具体报错信息
> 
> ![image](https://private-user-images.githubusercontent.com/51018113/301701211-8bc8a523-a301-4dd7-946e-fc7ed140db3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzkwODMsIm5iZiI6MTcwNjgzODc4MywicGF0aCI6Ii81MTAxODExMy8zMDE3MDEyMTEtOGJjOGE1MjMtYTMwMS00ZGQ3LTk0NmUtZmM3ZWQxNDBkYjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAxNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYzI1MmQ1ZTY1MDg2ZjllMGJmMWRmNWYzYWQ2ZjA3NzY0YjdkMzMyNTZmZDZkOTU2NzI2MDdkM2M0NTU3NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.psuJN6f5qgEfqtwSPjTyLSqJfDvhpVyhJQnlxRLqgww) 是这里么？

这个远程地址调用好像确实不对劲，难道还是反代的原因么，但我已经加了那个反代的配置了呀........

**Comment by zijiren233** [comment]
查看该请求的预览

**Comment by LikeGiver** [comment]
确实是b站多集一块加入会出现问题，我把番剧中单独的BV号拿出来作为单独视频是能正常加入并选择proxy的
<img width="1231" alt="image" src="https://github.com/synctv-org/synctv/assets/42694182/3b9dd912-ea5e-4eea-9538-e7506a8e0cb1">

**Comment by album-GitHub** [comment]
> 查看该请求的预览

预览那边提示movie proxy is not enabled

开启了普通视频代理后正常了.......所以番剧只能本机作为代理，客户端从服务端那边获取代理的视频么.......

**Comment by zijiren233** [comment]
b站番剧由于防盗链，浏览器端只能通过后端代理视频的方式实现

**Comment by album-GitHub** [comment]
> b站番剧由于防盗链，浏览器端只能通过后端代理视频的方式实现

原来如此，清楚了，感谢大佬
