### ISSUE TITLE
请问Docker持久化部署的映射目录填什么

### ISSUE THREAD

**Issue by sunny7010** [synctv-org/synctv#76]
![Clip_2024-02-01_22-50-36](https://github.com/synctv-org/synctv/assets/52040067/486c0090-c41a-4243-b316-570448156556)
看到程序自动创建了存储卷，但我想挂载到本机目录，请问容器目录是什么

**Comment by sunny7010** [comment]
/root/.synctv

**Comment by sunny7010** [comment]
使用该目录部署后，添加视频提示Websocket自动重连失败，无法使用

**Comment by zijiren233** [comment]
跟目录没关系的，是否添加了反向代理？反向代理配置参考文档中的配置

**Comment by sunny7010** [comment]
> 跟目录没关系的，是否添加了反向代理？反向代理配置参考文档中的配置

但是我删除目录映射部署就又可以了
