### ISSUE TITLE
新用户希望支持邮箱注册

### ISSUE THREAD

**Issue by fcwys** [synctv-org/synctv#87]
新用户希望支持邮箱注册，OAuth平台对于使用者不是很友好，且类似Github等国内访问不佳，希望支持邮箱注册新用户，后续密码重置和找回也方便些，谢谢！

**Comment by cyclestudy** [comment]
很需要

**Comment by fuckhere** [comment]
同求，希望增加注册功能

**Comment by zijiren233** [comment]
已支持 https://github.com/synctv-org/synctv/releases/tag/v0.4.5

**Comment by fuckhere** [comment]
> 已支持 https://github.com/synctv-org/synctv/releases/tag/v0.4.5

安装之后登陆界面没有注册选项呢，好像文档中也没看到对应内容，麻烦指点一下谢谢！

**Comment by zijiren233** [comment]
文档还没更新，需要到设置中填写smtp设置并开启邮件功能

**Comment by fuckhere** [comment]
> 文档还没更新，需要到设置中填写smtp设置并开启邮件功能

什么时候更新呢？是像OAuth2那样修改插件吗？不太清楚步骤，如果能及时更新一下，不胜感激

**Comment by fuckhere** [comment]
> 文档还没更新，需要到设置中填写smtp设置并开启邮件功能

好的，之前没看到root密码，没进后台。。。
