### ISSUE TITLE
有机会和小白羊第三方阿里云盘联动吗

### ISSUE THREAD

**Issue by Prince-cool** [synctv-org/synctv#9]
第三方的阿里云盘可以直接获取到视频m3u8链接，这样播放电影起来十分方便，是Electron打包，本质也是浏览器，所以应该有结合的可能，希望可以采纳

**Comment by huankong233** [comment]
> 第三方的阿里云盘可以直接获取到视频m3u8链接，这样播放电影起来十分方便，是Electron打包，本质也是浏览器，所以应该有结合的可能，希望可以采纳

可以搭配alist使用

**Comment by jiyekeji** [comment]
> > 第三方的阿里云盘可以直接获取到视频m3u8链接，这样播放电影起来十分方便，是Electron打包，本质也是浏览器，所以应该有结合的可能，希望可以采纳
> 
> 可以搭配alist使用

单编码大于h264的视频电脑上无法播放

**Comment by zijiren233** [comment]
目前已支持alist调用阿里云盘的m3u8

**Comment by a312354805** [comment]
> 目前已支持alist调用阿里云盘的m3u8

可以支持小雅吗
