### ISSUE TITLE
linux通过脚本一键部署后无法播放视频

### ISSUE THREAD

**Issue by NealScx** [synctv-org/synctv#90]
点击播放视频无反应    并且房间状态会变为close->reconnecting->open    点击三次就会提示：Websocket 自动重连失败！

`synctv.service - SyncTV Service
     Loaded: loaded (/etc/systemd/system/synctv.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-02-22 15:51:56 CST; 1min 43s ago
   Main PID: 229057 (synctv)
      Tasks: 7 (limit: 4636)
     Memory: 13.5M
     CGroup: /system.slice/synctv.service
             └─229057 /usr/bin/synctv server --data-dir /opt/synctv

2月 22 15:52:19 2024 synctv[229057]: time=2024-02-22 15:52:19 level=info msg=ws: room 123 user root connected
2月 22 15:52:45 2024 synctv[229057]: time=2024-02-22 15:52:45 level=info msg=ws: room 123 user root disconnected
2月 22 15:52:45 2024 synctv[229057]: time=2024-02-22 15:52:45 level=info msg=[GIN] 2024/02/22 - 15:52:45 | 200 | 26.332761296s |   220.197.4.167 | GET  >
2月 22 15:52:45 2024 synctv[229057]: time=2024-02-22 15:52:45 level=info msg=[GIN] 2024/02/22 - 15:52:45 | 204 |    1.139727ms |   220.197.4.167 | POST >
2月 22 15:52:45 2024 synctv[229057]: time=2024-02-22 15:52:45 level=info msg=[GIN] 2024/02/22 - 15:52:45 | 200 |      603.71µs |   220.197.4.167 | GET  >
2月 22 15:52:46 2024 synctv[229057]: time=2024-02-22 15:52:46 level=info msg=ws: room 123 user root connected
2月 22 15:52:47 2024 synctv[229057]: time=2024-02-22 15:52:47 level=info msg=ws: room 123 user root disconnected
2月 22 15:52:47 2024 synctv[229057]: time=2024-02-22 15:52:47 level=info msg=[GIN] 2024/02/22 - 15:52:47 | 200 |  1.131348207s |   220.197.4.167 | GET  >
2月 22 15:52:47 2024 synctv[229057]: time=2024-02-22 15:52:47 level=info msg=[GIN] 2024/02/22 - 15:52:47 | 204 |      447.85µs |   220.197.4.167 | POST >
2月 22 15:52:58 2024 synctv[229057]: time=2024-02-22 15:52:58 level=info msg=[GIN] 2024/02/22 - 15:52:58 | 204 |     382.792µs |   220.197.4.167 | POST >
~
`

![image](https://github.com/synctv-org/synctv/assets/85844254/f240e2d6-e725-4fa0-9656-382885ae8a25)

**Comment by zijiren233** [comment]
具体日志信息有吗，可能是发生了panic

**Comment by NealScx** [comment]
> 具体日志信息有吗，可能是发生了panic

请问是这个log文件吗
[log-2024-02-22T07-51-56.468.log](https://github.com/synctv-org/synctv/files/14392168/log-2024-02-22T07-51-56.468.log)

**Comment by NealScx** [comment]
> > 具体日志信息有吗，可能是发生了panic
> 
> 请问是这个log文件吗 [log-2024-02-22T07-51-56.468.log](https://github.com/synctv-org/synctv/files/14392168/log-2024-02-22T07-51-56.468.log)

![image](https://github.com/synctv-org/synctv/assets/85844254/88fefcbb-bb1a-4bf1-8a68-8bd6544a5106)
